# Generated by Django 2.1.7 on 2019-03-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('research_department_email', models.EmailField(max_length=254)),
                ('faculty_incharge_email', models.EmailField(max_length=254)),
                ('student_id', models.IntegerField(default=0)),
                ('phone_no', models.IntegerField(default=0)),
                ('research_area', models.CharField(blank=True, max_length=264, null=True)),
                ('frequency', models.IntegerField(default=0)),
                ('date_of_tenure_completion', models.DateField(auto_now=True)),
                ('date_of_query', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
