# Generated by Django 2.1.7 on 2019-03-02 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='date_of_tenure_completion',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
