# Generated by Django 2.1.7 on 2019-03-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20190302_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
