# Generated by Django 2.1.7 on 2019-03-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_student_model_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_status_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_model',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student_model',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student_status_model',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.student_model'),
        ),
    ]
