# Generated by Django 2.1.7 on 2019-03-02 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_auto_20190302_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='date_of_query',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
