# Generated by Django 2.1.7 on 2019-03-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_auto_20190302_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_model',
            name='date_of_query',
        ),
        migrations.RemoveField(
            model_name='student_model',
            name='date_of_tenure_completion',
        ),
    ]
