# Generated by Django 2.1.7 on 2019-03-02 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_auto_20190302_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='date_of_query',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
