# Generated by Django 2.1.7 on 2019-03-02 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0009_student_model_date_of_tenure_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='and_or_search_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('and_or_search', models.CharField(choices=[('and', 'and'), ('or', 'or')], default='and', max_length=5)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='student_model',
            name='date_of_tenure_completion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
