# Generated by Django 2.1.7 on 2019-03-02 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_auto_20190302_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='and_or_search_model',
            name='date_of_query',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
