# Generated by Django 2.1.7 on 2019-03-02 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_and_or_search_model_date_of_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf_indexing_model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_title', models.TextField(blank=True, null=True)),
                ('pdf_abstract', models.TextField(blank=True, null=True)),
                ('pdf_path', models.TextField(blank=True, null=True)),
                ('pdf_creation_date', models.CharField(blank=True, max_length=264, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pdf_query_model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='student_model',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pdf_query_model2',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.student_model'),
        ),
        migrations.AddField(
            model_name='pdf_query_model2',
            name='pdf_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.pdf_indexing_model2'),
        ),
    ]
