# Generated by Django 2.1.7 on 2019-03-03 06:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_auto_20190303_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_query_model2',
            name='date_of_query',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student_status_model',
            name='date_of_query',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
