# Generated by Django 2.1.7 on 2019-03-03 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_auto_20190303_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_data_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_query', models.DateTimeField(default=django.utils.timezone.now)),
                ('log', models.CharField(blank=True, max_length=264, null=True)),
                ('short_log', models.CharField(blank=True, max_length=264, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student_model',
            name='faculty_incharge_name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='faculty_incharge_phone',
            field=models.IntegerField(default=91),
        ),
        migrations.AddField(
            model_name='student_model',
            name='research_department_name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='research_department_phone',
            field=models.IntegerField(default=91),
        ),
        migrations.AlterField(
            model_name='pdf_indexing_model2',
            name='pdf_path',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='phone_no',
            field=models.IntegerField(default=91),
        ),
    ]
