# Generated by Django 2.1.7 on 2019-03-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='query_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('email', models.CharField(blank=True, max_length=264, null=True)),
                ('reg_no', models.IntegerField(default=0)),
            ],
        ),
    ]
