# Generated by Django 2.1.7 on 2019-03-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_model',
            name='keywords',
            field=models.TextField(null=True),
        ),
    ]
