# Generated by Django 2.1.7 on 2019-03-02 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20190302_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf_indexing_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_title', models.TextField(blank=True, null=True)),
                ('pdf_abstract', models.TextField(blank=True, null=True)),
                ('pdf_path', models.TextField(blank=True, null=True)),
                ('pdf_creation_date', models.CharField(blank=True, max_length=264, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pdf_query_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='query_model',
            name='date_of_query',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pdf_query_model',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.query_model'),
        ),
        migrations.AddField(
            model_name='pdf_query_model',
            name='pdf_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.pdf_indexing_model'),
        ),
    ]
