# Generated by Django 2.1.7 on 2019-03-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20190302_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query_model',
            name='student_id',
        ),
    ]
